import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { isLocale } from '@/lib/i18n';
import { getFloorProtectContent, type FloorProtectLocale } from '@/lib/floor-protect-content';
import { Breadcrumb } from '@/components/Breadcrumb';
import { AssetFigure } from '@/components/AssetFigure';
import { LightboxFigure } from '@/components/LightboxFigure';
import { productVisuals, visualFor } from '@/lib/product-visuals';
import { ProductHeroAmbient } from '@/components/ProductHeroAmbient';

export const metadata: Metadata = { title: 'PURE Floor Protect | Floor Protection & Abrasion Resistance | PURE', description: 'Ultra-thin lightly matt functional protection technology for high-use floor surfaces.' };
function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) { return <div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">{eyebrow}</span><h2>{title}</h2>{intro ? <p>{intro}</p> : null}</div>; }
function FloorDiagram({ locale }: { locale: FloorProtectLocale }) { return <div className="floor-protect-diagram" aria-label={locale === 'de' ? 'Technischer Visual-Slot für den Bodenaufbau' : 'Technical floor build-up visual slot'}>{['TRAFFIC / DIRT / CLEANING', '5–8 µm FUNCTIONAL PROTECTION LAYER', 'EXISTING SURFACE', 'FLOOR SUBSTRATE'].map((label, index) => <div className={`floor-protect-diagram__layer floor-protect-diagram__layer--${index}`} key={label}>{label}</div>)}</div>; }
const challengeDetails = {
  de: [
    ['MECHANISCHE BELASTUNG', 'Abrieb, Rollenlasten und intensive Nutzung beanspruchen die bestehende Oberfläche.'],
    ['HARZ & PIGMENTE', 'Harz, Gummiabrieb und Pigmente erhöhen den Reinigungsaufwand.'],
    ['REINIGUNGSCHEMIE', 'Häufige Reinigungszyklen können Oberfläche und Pflegezustand belasten.'],
    ['NUTZUNGSAUSFALL', 'Sperrzeiten und Grundreinigung beeinflussen den laufenden Betrieb.']
  ],
  en: [
    ['MECHANICAL WEAR', 'Abrasion, rolling loads and intensive use stress the existing surface.'],
    ['RESIN & PIGMENTS', 'Resin, rubber abrasion and pigments increase cleaning effort.'],
    ['CLEANING CHEMICALS', 'Frequent cleaning cycles can stress the surface and care condition.'],
    ['DOWNTIME', 'Closure periods and deep cleaning affect daily operation.']
  ]
} as const;

export default function PureFloorProtectPage() {
  const segment = headers().get('x-pure-locale') || 'en'; const locale: FloorProtectLocale = isLocale(segment) ? segment : 'en'; const t = getFloorProtectContent(locale); const asset = (de: string, en: string) => locale === 'de' ? de : en;
  return <><Breadcrumb items={[{ label: 'Start', href: locale === 'de' ? '/de' : '/en' }, { label: t.name }]} />
    <ProductHeroAmbient variant="floor" className="floor-protect-hero" image="Cinematic Bodennaht mit Wassertropfen.png" imageAlt={asset('Hochwertige horizontale Bodenoberfläche mit feiner funktionaler Schutzebene', 'High-quality horizontal floor surface with a fine functional protective layer')}><div className="container floor-protect-hero__grid"><div><p className="hero__eyebrow">{t.name}</p><h1>{t.heroTitle}</h1><p className="hero__subtitle">{t.heroSubtitle}</p><div className="surface-protect-facts">{t.facts.map(([value, label, note]) => <div key={value}><strong>{value}</strong><span>{label}</span>{note ? <small>{note}</small> : null}</div>)}</div><div className="hero__ctas"><a className="btn btn--primary" href="#technology">{t.explore}</a><a className="btn btn--secondary" href="#evidence">{t.evidenceCta}</a></div></div></div></ProductHeroAmbient>
    <section className="section section--surface"><div className="container"><Heading eyebrow={t.relationEyebrow} title={t.relationTitle} intro={t.relationCopy} /><div className="floor-protect-lineage"><div><strong>PURE SURFACE PROTECT</strong><span>Surface platform</span></div><b>↓</b><p>{locale === 'de' ? 'Anpassung an bodenspezifische Belastungen' : 'adaptation for floor-specific loads'}</p><b>↓</b><div><strong>PURE FLOOR PROTECT</strong><span>{locale === 'de' ? 'Floor application system' : 'Floor application system'}</span></div></div></div></section>
    <section className="section" id="challenge"><div className="container"><Heading eyebrow={t.challengeEyebrow} title={t.challengeTitle} intro={t.challengeCopy} /><div className="floor-challenge-grid">{challengeDetails[locale].map(([title, copy], index) => <article className="floor-challenge-card" data-surface={['abrasion', 'pigment', 'cleaning', 'downtime'][index]} key={title}><span aria-hidden="true">0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section section--surface" id="technology"><div className="container"><Heading eyebrow={t.techEyebrow} title={t.techTitle} /><div className="floor-protect-tech"><LightboxFigure file={visualFor(productVisuals.floorProtect.technology, locale)} alt={asset('Illustratives Funktionsprinzip des Bodenschutzes mit Bodenuntergrund, bestehender Oberfläche, Schutzschicht und Belastungen', 'Illustrative Floor Protect principle showing floor substrate, existing surface, protection layer and exposure')} caption={locale === 'de' ? 'Illustratives Technologievisual – keine maßstäbliche technische Zeichnung.' : 'Illustrative technology visual — not a scaled technical drawing.'} zoomLabel={locale === 'de' ? 'Vergrößern' : 'Enlarge'} closeLabel={locale === 'de' ? 'Schließen' : 'Close'} /><div className="surface-protect-steps">{t.steps.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></div></section>
    <section className="section" id="applications"><div className="container"><Heading eyebrow={t.applicationsEyebrow} title={t.applicationsTitle} /><div className="floor-application-features"><article className="floor-application-feature"><LightboxFigure file={visualFor(productVisuals.floorProtect.sports, locale)} alt={asset('Illustratives Sporthallenbodenvisual mit Vorher-/Nachher-Kommunikation', 'Illustrative sports-floor visual with before-and-after communication')} caption={asset('Illustratives Kommunikationsvisual – keine reale dokumentierte Referenz.', 'Illustrative communication visual — not a real documented reference.')} zoomLabel={locale === 'de' ? 'Vergrößern' : 'Enlarge'} closeLabel={locale === 'de' ? 'Schließen' : 'Close'} /><div><h3>{t.applications[0][0]}</h3><p>{t.applications[0][1]}</p></div></article><article className="floor-application-feature"><LightboxFigure file={visualFor(productVisuals.floorProtect.publicBuildings, locale)} alt={asset('Illustratives Visual eines sauberen Bodens für stark frequentierte öffentliche Räume', 'Illustrative visual of a clean floor for high-use public spaces')} caption={asset('Illustratives Anwendungsvisual – keine reale dokumentierte Referenz.', 'Illustrative application visual — not a real documented reference.')} zoomLabel={locale === 'de' ? 'Vergrößern' : 'Enlarge'} closeLabel={locale === 'de' ? 'Schließen' : 'Close'} /><div><h3>{t.applications[1][0]}</h3><p>{t.applications[1][1]}</p></div></article></div><div className="floor-protect-applications floor-protect-applications--icons">{t.applications.slice(2).map(([title, copy], index) => <article className="floor-application-card" data-surface={['matte', 'reflection', 'abrasion', 'pigment'][index]} key={title}><span aria-hidden="true">{String(index + 3).padStart(2, '0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section section--surface" id="evidence"><div className="container"><Heading eyebrow={t.evidenceEyebrow} title={t.evidenceTitle} intro={t.evidenceScope} /><div className="floor-protect-evidence">{t.evidence.map(([title, standard, copy]) => <article key={title}><span>{title}</span><strong>{standard}</strong><p>{copy}</p><small>{locale === 'de' ? 'SOURCE VERIFICATION REQUIRED: Originalprüfbericht/Zuordnung im Datenbestand nicht vollständig verifiziert.' : 'SOURCE VERIFICATION REQUIRED: Original report / assignment not fully verified in the data store.'}</small>{title.toLowerCase().includes('klasse 1') ? <em>{locale === 'de' ? 'Dokumentierte Testbasis · Originalquelle/Produktzuordnung in Verifikation' : 'Documented test basis · Original source/product assignment under verification'}</em> : null}</article>)}</div></div></section>
    <section className="section" id="quality"><div className="container"><Heading eyebrow={t.qaEyebrow} title={t.qaTitle} /><div className="surface-protect-qa">{t.qa.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="surface-protect-statement">{t.qaStatement}</p><div className="floor-protect-warning"><h3>{t.slipTitle}</h3><p>{t.slipCopy}</p></div><div className="floor-protect-warning"><h3>{t.serviceTitle}</h3><p>{t.serviceCopy}</p></div></div></section>
    <section className="section section--surface" id="lifecycle"><div className="container"><Heading eyebrow={t.lifecycleEyebrow} title={t.lifecycleTitle} /><div className="surface-protect-lifecycle">{t.lifecycleFactors.map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section className="section" id="limits"><div className="container"><Heading eyebrow={t.limitsEyebrow} title={t.limitsTitle} /><div className="surface-protect-limits"><article><h3>{locale === 'de' ? 'DOKUMENTIERT / TESTBASIS' : 'DOCUMENTED / TEST BASIS'}</h3><ul>{t.strengths.map((x) => <li key={x}>{x}</li>)}</ul></article><article><h3>{locale === 'de' ? 'OBJEKTSPEZIFISCH ZU PRÜFEN' : 'OBJECT-SPECIFIC VERIFICATION REQUIRED'}</h3><ul>{t.limits.map((x) => <li key={x}>{x}</li>)}</ul></article></div><div className="surface-protect-public"><h3>{t.publicTitle}</h3><div>{t.publicItems.map((x) => <span key={x}>{x}</span>)}</div></div></div></section>
    <section className="section section--surface"><div className="container"><div className="final-cta"><h2>{t.finalTitle}</h2><p>{t.finalCopy}</p><div className="hero__ctas" style={{ justifyContent: 'center' }}><a className="btn btn--primary" href="#quality">{t.project}</a><a className="btn btn--secondary btn--dark" href="#challenge">{t.test}</a></div></div></div></section>
  </>;
}
