import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { isLocale } from '@/lib/i18n';
import { getFloorProtectContent, type FloorProtectLocale } from '@/lib/floor-protect-content';
import { Breadcrumb } from '@/components/Breadcrumb';
import { AssetFigure } from '@/components/AssetFigure';

export const metadata: Metadata = { title: 'PURE Floor Protect | Floor Protection & Abrasion Resistance | PURE', description: 'Ultra-thin lightly matt functional protection technology for high-use floor surfaces.' };
function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) { return <div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">{eyebrow}</span><h2>{title}</h2>{intro ? <p>{intro}</p> : null}</div>; }
function FloorDiagram({ locale }: { locale: FloorProtectLocale }) { return <div className="floor-protect-diagram" aria-label={locale === 'de' ? 'Technischer Visual-Slot für den Bodenaufbau' : 'Technical floor build-up visual slot'}>{['TRAFFIC / DIRT / CLEANING', '5–8 µm FUNCTIONAL PROTECTION LAYER', 'EXISTING SURFACE', 'FLOOR SUBSTRATE'].map((label, index) => <div className={`floor-protect-diagram__layer floor-protect-diagram__layer--${index}`} key={label}>{label}</div>)}</div>; }
export default function PureFloorProtectPage() {
  const segment = headers().get('x-pure-locale') || 'en'; const locale: FloorProtectLocale = isLocale(segment) ? segment : 'en'; const t = getFloorProtectContent(locale); const asset = (de: string, en: string) => locale === 'de' ? de : en;
  return <><Breadcrumb items={[{ label: 'Start', href: locale === 'de' ? '/de' : '/en' }, { label: t.name }]} />
    <section className="hero floor-protect-hero"><div className="container floor-protect-hero__grid"><div><p className="hero__eyebrow">{t.name}</p><h1>{t.heroTitle}</h1><p className="hero__subtitle">{t.heroSubtitle}</p><div className="surface-protect-facts">{t.facts.map(([value, label]) => <div key={value}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="hero__ctas"><a className="btn btn--primary" href="#technology">{t.explore}</a><a className="btn btn--secondary" href="#evidence">{t.evidenceCta}</a></div></div><AssetFigure file="01_floor_hero_sporthall_source.jpeg" alt={asset('Kommunikationsvisual einer Sporthalle für PURE FLOOR PROTECT', 'PURE FLOOR PROTECT sports hall application communication visual')} caption={t.heroCaption} priority /></div></section>
    <section className="section section--surface"><div className="container"><Heading eyebrow={t.relationEyebrow} title={t.relationTitle} intro={t.relationCopy} /><div className="floor-protect-relation"><strong>PURE SURFACE PROTECT</strong><span>↓</span><strong>PURE FLOOR PROTECT</strong></div></div></section>
    <section className="section" id="challenge"><div className="container"><Heading eyebrow={t.challengeEyebrow} title={t.challengeTitle} intro={t.challengeCopy} /><div className="surface-protect-four-grid">{t.challengeCards.map((title) => <article className="surface-protect-card" key={title}><h3>{title}</h3></article>)}</div></div></section>
    <section className="section section--surface" id="technology"><div className="container"><Heading eyebrow={t.techEyebrow} title={t.techTitle} /><div className="floor-protect-tech"><FloorDiagram locale={locale} /><div className="surface-protect-steps">{t.steps.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div><p className="surface-protect-note">{locale === 'de' ? 'Visual-Slot: Floor Protect Technical Cross-Section – FEHLENDES VISUAL.' : 'Visual slot: Floor Protect Technical Cross-Section — MISSING VISUAL.'}</p></div></section>
    <section className="section" id="applications"><div className="container"><Heading eyebrow={t.applicationsEyebrow} title={t.applicationsTitle} /><div className="floor-protect-applications">{t.applications.map(([title, copy]) => <article className="surface-protect-card" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section section--surface" id="evidence"><div className="container"><Heading eyebrow={t.evidenceEyebrow} title={t.evidenceTitle} intro={t.evidenceScope} /><div className="floor-protect-evidence">{t.evidence.map(([title, standard, copy]) => <article key={title}><span>{title}</span><strong>{standard}</strong><p>{copy}</p><small>{locale === 'de' ? 'SOURCE VERIFICATION REQUIRED: Originalprüfbericht/Zuordnung im Datenbestand nicht vollständig verifiziert.' : 'SOURCE VERIFICATION REQUIRED: Original report / assignment not fully verified in the data store.'}</small></article>)}</div></div></section>
    <section className="section" id="quality"><div className="container"><Heading eyebrow={t.qaEyebrow} title={t.qaTitle} /><div className="surface-protect-qa">{t.qa.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="surface-protect-statement">{t.qaStatement}</p><div className="floor-protect-warning"><h3>{t.slipTitle}</h3><p>{t.slipCopy}</p></div><div className="floor-protect-warning"><h3>{t.serviceTitle}</h3><p>{t.serviceCopy}</p></div></div></section>
    <section className="section section--surface" id="lifecycle"><div className="container"><Heading eyebrow={t.lifecycleEyebrow} title={t.lifecycleTitle} /><div className="surface-protect-lifecycle">{t.lifecycleFactors.map((item) => <span key={item}>{item}</span>)}</div></div></section>
    <section className="section" id="limits"><div className="container"><Heading eyebrow={t.limitsEyebrow} title={t.limitsTitle} /><div className="surface-protect-limits"><article><h3>{locale === 'de' ? 'DOKUMENTIERT / TESTBASIS' : 'DOCUMENTED / TEST BASIS'}</h3><ul>{t.strengths.map((x) => <li key={x}>{x}</li>)}</ul></article><article><h3>{locale === 'de' ? 'OBJEKTSPEZIFISCH ZU PRÜFEN' : 'OBJECT-SPECIFIC VERIFICATION REQUIRED'}</h3><ul>{t.limits.map((x) => <li key={x}>{x}</li>)}</ul></article></div><div className="surface-protect-public"><h3>{t.publicTitle}</h3><div>{t.publicItems.map((x) => <span key={x}>{x}</span>)}</div></div></div></section>
    <section className="section section--surface"><div className="container"><div className="final-cta"><h2>{t.finalTitle}</h2><p>{t.finalCopy}</p><div className="hero__ctas" style={{ justifyContent: 'center' }}><a className="btn btn--primary" href="#quality">{t.project}</a><a className="btn btn--secondary btn--dark" href="#challenge">{t.test}</a></div></div></div></section>
  </>;
}
