import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { isLocale } from '@/lib/i18n';
import { getFireProtectContent, type FireProtectLocale } from '@/lib/fire-protect-content';
import { Breadcrumb } from '@/components/Breadcrumb';
import { AssetFigure } from '@/components/AssetFigure';
import { LightboxFigure } from '@/components/LightboxFigure';
import { productVisuals } from '@/lib/product-visuals';
import { ProductHeroAmbient } from '@/components/ProductHeroAmbient';
import { SurfaceCard } from '@/components/SurfaceCard';

const applicationAssets = [
  'Brennendes Holzhaus am Seeufer.png',
  'Brennendes Reetdach im Abendlicht.png',
  'Brennendes Rathaus im Feuerwehreinsatz.png',
  'Industriebrand mit kämpfenden Feuerwehrleuten.png',
  'BESS-Brand mit Feuerwehr im Einsatz.png',
  'Dramatischer Waldbrandeinsatz bei Sonnenuntergang.png'
] as const;

export const metadata: Metadata = { title: 'PURE Fire Protect | Functional Fire Protection | PURE', description: 'Functional fire protection for defined systems, visible materials and controlled evidence.' };
function Heading({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) { return <div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">{eyebrow}</span><h2>{title}</h2>{intro ? <p>{intro}</p> : null}</div>; }
export default function PureFireProtectPage() {
  const segment = headers().get('x-pure-locale') || 'en'; const locale: FireProtectLocale = isLocale(segment) ? segment : 'en'; const t = getFireProtectContent(locale); const asset = (de: string, en: string) => locale === 'de' ? de : en;
  return <><Breadcrumb items={[{ label: 'Start', href: locale === 'de' ? '/de' : '/en' }, { label: t.name }]} />
    <ProductHeroAmbient variant="fire" className="fire-protect-hero" image="Feuer trifft auf Schutzschicht.png" imageAlt={asset('Illustratives Materialprinzip: Hitze hinter einer funktionalen Schutzschicht', 'Illustrative material principle: heat behind a functional protective layer')}><div className="container fire-protect-hero__grid"><div><p className="hero__eyebrow">{t.name}</p><h1>{t.heroTitle}</h1><p className="hero__subtitle">{t.heroSubtitle}</p><div className="hero__ctas"><a className="btn btn--primary" href="#technology">{t.heroCta}</a><a className="btn btn--secondary" href="#evidence">{t.evidenceCta}</a></div></div></div></ProductHeroAmbient>
    <section className="section" id="challenge"><div className="container"><Heading eyebrow={t.challengeEyebrow} title={t.challengeTitle} intro={t.challengeCopy} /><div className="fire-protect-three-grid">{t.challengeCards.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="fire-protect-rule">{t.statement}</div></div></section>
    <section className="section section--surface"><div className="container"><Heading eyebrow={t.profileEyebrow} title={t.profileTitle} /><div className="fire-protect-profile">{t.profileFacts.map(([title, value]) => <div key={title}><strong>{title}</strong><span>{value}</span></div>)}</div><p className="surface-protect-note">{t.profileNote}</p></div></section>
    <section className="section" id="technology"><div className="container"><Heading eyebrow={t.mechanismEyebrow} title={t.mechanismTitle} /><div className="fire-protect-mechanism"><div className="fire-protect-mechanism__layers">{t.mechanism.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><LightboxFigure file={productVisuals.fireProtect.mechanism} alt={asset('Technisches Konzeptvisual für transparente Schutzschicht, Hitze, mineralische Schaumschicht und Systemnachweis', 'Technical concept visual for transparent protective layer, heat, mineral foam barrier and system evidence')} caption={locale === 'de' ? 'Illustratives technisches Mechanismusvisual – kein eigenständiger Prüf- oder Klassifizierungsnachweis.' : 'Illustrative technical mechanism visual — not an independent test or classification result.'} zoomLabel={locale === 'de' ? 'Vergrößern' : 'Enlarge'} closeLabel={locale === 'de' ? 'Schließen' : 'Close'} /></div></div></section>
    <section className="section section--surface"><div className="container"><Heading eyebrow={t.architectureEyebrow} title={t.architectureTitle} /><div className="fire-protect-architecture">{t.architecture.map(([title, copy], index) => <article key={title}><span className="fire-protect-route-anchor" aria-hidden="true"><i /><i /><i /></span><span className="fire-protect-architecture__number">0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="fire-protect-rule">{t.systemRule}</div></div></section>
    <section className="section" id="applications"><div className="container"><Heading eyebrow={t.applicationsEyebrow} title={t.applicationsTitle} /><div className="fire-protect-applications">{t.applications.map(([title, copy], index) => <SurfaceCard surface="fire-context" backgroundAsset={applicationAssets[index]} key={title}><h3>{title}</h3><p>{copy}</p></SurfaceCard>)}</div><AssetFigure file="04_fire_application_worlds.jpeg" alt={asset('Illustratives Anwendungsvisual verschiedener PURE FIRE PROTECT Anwendungswelten', 'Illustrative application overview of PURE FIRE PROTECT application worlds')} caption={locale === 'de' ? 'Illustratives Application-Overview-Visual – keine automatisch zugelassene oder realisierte Anwendung.' : 'Illustrative application overview — not an automatically approved or implemented application.'} /></div></section>
    <section className="section section--surface" id="evidence"><div className="container"><Heading eyebrow={t.evidenceEyebrow} title={t.evidenceTitle} intro={t.evidenceScope} /><div className="fire-protect-evidence"><div><h3>{t.sbiTitle}</h3>{t.sbi.map(([title, value]) => <div className="fire-protect-evidence-row" key={title}><strong>{title}</strong><span>{value}</span></div>)}</div><AssetFigure file="02_fire_test_lab.jpeg" alt={asset('Illustratives Testlabor-Kommunikationsvisual für PURE FIRE PROTECT', 'Illustrative testing-context communication visual for PURE FIRE PROTECT')} caption={locale === 'de' ? 'TESTING CONTEXT VISUAL – nicht als fotografische Dokumentation des konkreten Prüfereignisses.' : 'TESTING CONTEXT VISUAL — not a photographic record of the specific test event.'} /></div><p className="fire-protect-caveat">{t.caveat}</p><div className="fire-protect-smoke"><h3>{t.smokeTitle}</h3>{t.smoke.map(([title, copy]) => <div key={title}><strong>{title}</strong><p>{copy}</p></div>)}</div></div></section>
    <section className="section" id="quality"><div className="container"><Heading eyebrow={t.qaEyebrow} title={t.qaTitle} /><div className="fire-protect-qa">{t.qa.map(([title, copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><AssetFigure file="05_fire_quality_assurance.jpeg" alt={asset('Illustratives QA-Kommunikationsvisual für die PURE FIRE PROTECT Verarbeitung', 'Illustrative application and quality-assurance visual for PURE FIRE PROTECT')} caption={locale === 'de' ? 'APPLICATION / QA VISUAL – keine automatisch dokumentierte Baustelle.' : 'APPLICATION / QA VISUAL — not an automatically documented construction site.'} /><p className="surface-protect-statement">{t.qaStatement}</p></div></section>
    <section className="section section--surface"><div className="container"><Heading eyebrow={t.regulatoryEyebrow} title={t.regulatoryTitle} /><div className="fire-protect-regulatory">{t.regulatory.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="fire-protect-rule">{t.regulatoryRule}</div></div></section>
    <section className="section"><div className="container"><Heading eyebrow={t.sustainabilityEyebrow} title={t.sustainabilityTitle} /><div className="fire-protect-columns"><article><h3>{locale === 'de' ? 'DOKUMENTIERTE BASIS' : 'DOCUMENTED BASIS'}</h3><ul>{t.sustainability.map((x) => <li key={x}>{x}</li>)}</ul></article><article><h3>{locale === 'de' ? 'WIRTSCHAFTLICHE LOGIK' : 'ECONOMIC LOGIC'}</h3><p>{t.economicTitle}</p><ul>{t.economic.map((x) => <li key={x}>{x}</li>)}</ul></article></div></div></section>
    <section className="section section--surface"><div className="container"><Heading eyebrow="RESPONSIBLE CLAIMS" title={locale === 'de' ? 'Was dokumentiert ist – und was nicht pauschal folgt.' : 'What is documented — and what does not follow generally.'} /><div className="fire-protect-columns"><article><h3>{locale === 'de' ? 'DOKUMENTIERTE BASIS' : 'DOCUMENTED BASIS'}</h3><ul>{t.strengths.map((x) => <li key={x}>{x}</li>)}</ul></article><article><h3>{locale === 'de' ? 'NICHT PAUSCHAL ABLEITBAR' : 'NOT GENERALLY DERIVABLE'}</h3><ul>{t.limits.map((x) => <li key={x}>{x}</li>)}</ul></article></div></div></section>
    <section className="section"><div className="container"><div className="final-cta"><h2>{t.finalTitle}</h2><p>{t.finalCopy}</p><div className="hero__ctas" style={{ justifyContent: 'center' }}><a className="btn btn--primary" href="#quality">{t.project}</a><a className="btn btn--secondary btn--dark" href="#evidence">{t.route}</a></div></div></div></section>
  </>;
}
