import Link from 'next/link';
import { getProductBySlug, getSystemsByProduct, getValueById } from '@/lib/data';
import { Breadcrumb } from './Breadcrumb';
import { EvidenceBadge } from './EvidenceBadge';
import { LightboxFigure } from './LightboxFigure';
import { SystemCard } from './SystemCard';
import { TechnicalValue } from './TechnicalValue';
import { TechnicalVisual } from './TechnicalVisual';
import { PureThermoUValueCalculator } from './PureThermoUValueCalculator';
import { ThermoParityHero } from './ProductParityHero';
import { SurfaceCard } from './SurfaceCard';

const CORE_VALUE_IDS = ['VAL-PT-LAMBDA-001', 'VAL-PT-V-001', 'VAL-PT-SD-001', 'VAL-PT-MU-001', 'VAL-PT-CONSUMPTION-001', 'VAL-PT-SPRAY-LAYER-001', 'VAL-PT-R-05MM-001', 'VAL-PT-R-10MM-001', 'VAL-PT-R-20MM-001', 'VAL-PT-R-30MM-001'];
const VALUE_LABELS: Record<string, string> = {
  'VAL-PT-LAMBDA-001': 'Thermal conductivity', 'VAL-PT-V-001': 'Water-vapour transmission rate', 'VAL-PT-SD-001': 'Water-vapour diffusion-equivalent air-layer thickness', 'VAL-PT-MU-001': 'Water-vapour diffusion resistance factor', 'VAL-PT-CONSUMPTION-001': 'Consumption', 'VAL-PT-SPRAY-LAYER-001': 'Layer thickness per spray pass', 'VAL-PT-R-05MM-001': 'Thermal resistance at 5 mm', 'VAL-PT-R-10MM-001': 'Thermal resistance at 10 mm', 'VAL-PT-R-20MM-001': 'Thermal resistance at 20 mm', 'VAL-PT-R-30MM-001': 'Thermal resistance at 30 mm'
};
const SYSTEM_HREFS: Record<string, string> = { 'SYS-PT-INT-001': '/en/systems/pure-thermo-interior', 'SYS-PT-EXT-001': '/en/systems/pure-thermo-exterior', 'SYS-PT-DET-001': '/en/systems/pure-thermo-detail', 'SYS-PT-FIRE-001': '/en/systems/pure-thermo-fire' };
const SYSTEM_SUMMARIES: Record<string, string> = {
  'SYS-PT-DET-001': 'Application focus for geometrically demanding details and areas with limited build-up height; the system definition is being developed.',
  'SYS-PT-EXT-001': 'Exterior route for defined existing mineral façades; the complete exterior and fire evidence package is still being developed.',
  'SYS-PT-FIRE-001': 'Technically plausible combination route requiring testing; no Euroclass before testing and classification of the complete build-up.'
};
const EVIDENCE_GROUPS = [{ evidenceClass: 'A' as const, title: 'A – EXTERNALLY TESTED' }, { evidenceClass: 'B' as const, title: 'B – INTERNALLY DOCUMENTED' }, { evidenceClass: 'C' as const, title: 'C – CALCULATED / MODELLED' }];
const applicationFields = ['Reveals & connections', 'Cold interior surfaces', 'Existing-building details', 'Complex geometries', 'Basement areas', 'Special technical surfaces after assessment'];
const applicationSurfaces = ['detail', 'mineral', 'existing', 'contour', 'mineral', 'layer'] as const;
const applicationAssets = ['Detaillierter Fensteranschluss mit Dämmfassade.png', 'Kühler Keller, warmes Raumklima.png', 'Moderne Fassade im Abendlicht.png', 'Ornate Pariser Jugendstilfassade im Sonnenlicht.png', 'Heller, aufgeräumter Kellerraum.png', 'Moderne Fassade mit Seeblick.png'] as const;
const journeyAssets = ['Moderne Fassade im Abendlicht.png', 'Detaillierter Fensteranschluss mit Dämmfassade.png', 'Ornate Pariser Jugendstilfassade im Sonnenlicht.png', 'Moderne Fassade mit Seeblick.png'] as const;
const limits = ['No general statement that PURE THERMO replaces conventional insulation systems.', 'No general energy-saving percentages.', 'No general payback statements.', 'No general fire classification for PURE THERMO + PURE FIRE before complete system testing.', 'No general funding eligibility statement.', 'No general mould-prevention claim.', 'No unsupported sound-insulation, recycling or circular-economy claims.'];
const faqItems = [
  ['Can PURE THERMO replace a conventional external thermal insulation composite system?', 'Not generally. Suitability depends on the component, the required energy-performance target, layer thickness and the approved system build-up.'],
  ['Is PURE THERMO eligible for KfW funding?', 'No general KfW product approval is claimed. Funding eligibility depends on the project, measure and evidence provided.'],
  ['Has the lambda value been externally tested?', 'For THERM 4410, a thermal conductivity of 0.0335 ± 0.0003 W/(m·K) was externally determined according to DIN EN 12664:2001-05. Assignment to the current PURE THERMO formulation still has to be documented clearly.'],
  ['Does PURE THERMO prevent mould?', 'No general mould-prevention claim is approved. Surface temperature, moisture and structural causes must be assessed for each project.']
];

export function PureThermoEnglishFullPage() {
  const product = getProductBySlug('pure-thermo');
  if (!product) return null;
  const values = CORE_VALUE_IDS.map((id) => getValueById(id)).filter((value): value is NonNullable<typeof value> => Boolean(value));
  const systems = getSystemsByProduct(product.id);
  return <>
    <Breadcrumb items={[{ label: 'Home', href: '/en' }, { label: 'Products' }, { label: 'Pure Thermo' }]} />
    <ThermoParityHero eyebrow="PURE THERMO" title="Thermal function at minimal build-up height." subtitle="A thin, applicable coating technology for thermally relevant component areas, complex geometries and applications with limited installation space." primary={{ label: 'View system build-up', href: '#system-build-up' }} secondary={{ label: 'Technical evidence', href: '/en/evidence/EVD-PT-THERM-001' }} />

    <section className="section"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">THE CHALLENGE</span><h2>When installation space becomes a technical constraint.</h2></div><div className="problem-grid">
      <div className="problem-card"><h3>Limited build-up height</h3><p>Conventional systems reach structural limits where an additional build-up cannot be accommodated.</p></div><div className="problem-card"><h3>Complex geometries</h3><p>Details and connections cannot always be addressed with a conventional installed solution.</p></div><div className="problem-card"><h3>Existing connections</h3><p>Retrofit solutions must work where existing elements, component boundaries and constructions are already fixed.</p></div><div className="problem-card"><h3>Local thermal hotspots</h3><p>For certain detail problems, targeted local thermal treatment may complement the overall measure.</p></div><div className="problem-card"><h3>Hard-to-reach areas</h3><p>Individual surfaces or details cannot always be addressed with conventional systems without extensive construction work.</p></div>
    </div></div></section>

    <section className="section section--surface"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">WHERE IS IT USED?</span><h2>Thermal function at critical points.</h2></div><div className="card-grid card-grid--3 thermo-material-grid">{applicationFields.map((item, index) => <SurfaceCard className="application-card" surface={applicationSurfaces[index]} backgroundAsset={applicationAssets[index]} key={item}><span className="application-card__name">{item}</span></SurfaceCard>)}</div></div></section>

    <section className="section" id="system-build-up"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">SYSTEM BUILD-UP</span><h2>From component to functional layer.</h2></div><div className="split-section split-section--balanced"><div className="split-section__media"><LightboxFigure file="Bauteilquerschnitt.png" alt="Component cross-section with a thin PURE THERMO functional layer on the substrate" caption="Substrate → PURE THERMO functional layer → defined system layer(s)" zoomLabel="Enlarge" closeLabel="Close" /></div><div className="split-section__text"><p>The thermal effect results from the interaction of substrate, applied functional layer and the specific component build-up.</p><p>PURE THERMO is not designed as generic full thermal insulation, but as a targeted functional layer for thermally relevant areas with limited space and complex boundary conditions.</p><LightboxFigure file="pure Thermo Basic.png" alt="PURE THERMO Basic as a layer system in practical application" caption="Detailed system representation for technical inspection." zoomLabel="Enlarge" closeLabel="Close" /></div></div></div></section>

    <section className="section section--surface"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">HOW DOES THE MATERIAL WORK?</span><h2>The material principle can be explained in a few steps.</h2></div><div className="material-story"><div className="material-story__visual"><LightboxFigure file="Aerogel Funktion.png" alt="Functional principle: the aerogel structure influences heat transport within the thin layer" caption="Macro: the material structure influences heat transport." zoomLabel="Enlarge" closeLabel="Close" /></div><div className="material-story__copy"><p className="lede">The relevant effect results from the structure of the layer, not from a large material mass.</p><p>Within the nanoporous architecture, heat transport through the functional layer is reduced. This allows a very thin coating to be effective for defined thermal applications. The specific effect must always be assessed in the relevant component and system context.</p></div></div><div className="material-detail" style={{ marginTop: 'var(--space-5)' }}><div className="material-detail__image"><LightboxFigure file="Materialstruktur.png" alt="Detailed view of the nanoporous PURE THERMO material structure" caption="Material structure as the basis of the thermal function." zoomLabel="Enlarge" closeLabel="Close" /></div><div className="material-detail__text"><h3>Technically precise wording</h3><p>PURE THERMO is a material and coating technology for defined thermal functional areas. Its effect is assessed in a clear system context, not as a general replacement for every build-up.</p></div></div></div></section>

    <section className="section"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">APPLICATION FIELDS</span><h2>Typical applications and system contexts.</h2></div><div className="application-journey thermo-material-grid"><SurfaceCard className="journey-card" surface="existing" backgroundAsset={journeyAssets[0]}><div className="journey-card__body"><h3>Existing buildings</h3><p>Components with limited installation space or existing constraints.</p></div></SurfaceCard><SurfaceCard className="journey-card" surface="detail" backgroundAsset={journeyAssets[1]}><div className="journey-card__body"><h3>Detail areas</h3><p>Connections, reveals and complex transitions.</p></div></SurfaceCard><SurfaceCard className="journey-card" surface="contour" backgroundAsset={journeyAssets[2]}><div className="journey-card__body"><h3>Complex geometries</h3><p>Functional areas with irregular surfaces and system integration.</p></div></SurfaceCard><SurfaceCard className="journey-card" surface="layer" backgroundAsset={journeyAssets[3]}><div className="journey-card__body"><h3>Technical surfaces</h3><p>Thermally relevant areas with a defined testing and system logic.</p></div></SurfaceCard></div></div></section>

    <section className="section section--surface"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">APPLICATION OVERVIEW</span><h2>More than insulation alone.</h2></div><TechnicalVisual locale="en" visual="overview" altDe="" altEn="Illustrative overview of potential PURE THERMO application scenarios in a building section." captionDe="" captionEn="Illustrative overview of potential application scenarios. Technical suitability and the specific system build-up must be assessed for each application and project." zoomable /></div></section>

    <section className="section section--surface" id="kennwerte"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">TECHNICAL CORE VALUES</span><h2>The essential parameters as actual product data.</h2></div><div className="warning-panel" role="alert"><span className="warning-panel__label">TEST STATUS</span>The external test report refers to THERM 4410. Formal documentation assigning it to the current PURE THERMO version is maintained separately.</div><div className="technical-value-groups">{EVIDENCE_GROUPS.map((group) => { const groupValues = values.filter((value) => value.evidence_class === group.evidenceClass); if (!groupValues.length) return null; return <section className="technical-value-group" key={group.evidenceClass} aria-labelledby={`values-${group.evidenceClass}`}><div className="technical-value-group__heading"><h3 id={`values-${group.evidenceClass}`}>{group.title}</h3><EvidenceBadge evidenceClass={group.evidenceClass} locale="en" /></div><div className="technical-value-grid">{groupValues.map((value) => <TechnicalValue key={value.id} value={value} locale="en" label={VALUE_LABELS[value.id]} warning={value.product_mapping?.warning_de || value.warning_de ? 'Product assignment and stated limitations remain applicable to this value.' : undefined} />)}</div></section>; })}</div><PureThermoUValueCalculator locale="en" /></div></section>

    <section className="section"><div className="container"><div className="proof-panel"><div className="proof-panel__header"><span className="section-heading__eyebrow">EXTERNALLY TESTED</span><h2>λ = 0.0335 W/(m·K)</h2></div><div className="proof-panel__meta"><span>Kiwa GmbH / MPA Berlin-Brandenburg</span><span>DIN EN 12664</span></div><p>The evidence for THERM 4410 was determined under documented test conditions according to DIN EN 12664. Key limitations concern assignment of the tested subject to the current PURE THERMO version and transferability to other system build-ups.</p><div className="hero__ctas"><Link className="btn btn--primary" href="/en/evidence/EVD-PT-THERM-001">Technical evidence</Link></div></div></div></section>

    <section className="section section--surface"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">SYSTEM ROUTES</span><h2>PURE THERMO as the basis for defined system development.</h2></div><div className="system-routes"><div className="system-routes__root"><span className="section-heading__eyebrow">BASE TECHNOLOGY</span><h3>PURE THERMO</h3><p>Shared thermal functional basis for defined system and application routes.</p></div><div className="system-routes__children">{systems.map((system) => <SystemCard key={system.id} system={system} href={SYSTEM_HREFS[system.id]} locale="en" summary={SYSTEM_SUMMARIES[system.id]} />)}</div></div></div></section>

    <section className="section"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">WHERE PURE THERMO IS USEFUL – AND WHERE IT IS NOT</span><h2>Limitations are part of technical credibility.</h2></div><div className="limits-grid"><div className="limits-panel limits-panel--strengths"><h3>Where PURE THERMO plays to its strengths</h3><ul><li>limited build-up height</li><li>detail areas</li><li>complex geometries</li><li>local thermal functions</li><li>existing connections</li></ul></div><div className="limits-panel limits-panel--caution"><h3>What cannot be derived generally</h3><ul>{limits.map((item) => <li key={item}>{item}</li>)}</ul></div></div></div></section>

    <section className="section section--surface"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">ECONOMICS</span><h2>Beyond material cost alone.</h2></div><LightboxFigure file="TCO Logik.png" alt="PURE THERMO total-cost logic covering material, installation, operation and lifecycle" caption="Economics can comprise material, installation, intervention depth and lifecycle – a qualitative logic where no robust project calculation is available." zoomLabel="Enlarge" closeLabel="Close" /></div></section>

    <section className="section"><div className="container"><div className="section-heading section-heading--narrow"><span className="section-heading__eyebrow">FAQ</span><h2>Frequently asked questions about PURE THERMO.</h2></div><div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-2)' }}>{faqItems.map(([heading, text]) => <details key={heading} style={{ border: '1px solid var(--color-border)', borderRadius: 'var(--radius-md)', padding: 'var(--space-3)' }}><summary style={{ fontWeight: 600, cursor: 'pointer', color: 'var(--color-navy)' }}>{heading}</summary><p style={{ marginTop: 'var(--space-2)', color: 'var(--color-text-muted)' }}>{text}</p></details>)}</div></div></section>

    <section className="section section--surface"><div className="container"><div className="final-cta"><p className="final-cta__lead">Let us assess whether PURE THERMO is suitable for your component.</p><h2>Discuss a project</h2><div className="hero__ctas" style={{ justifyContent: 'center' }}><Link className="btn btn--primary" href="/en/project-request">Discuss a project</Link><Link className="btn btn--secondary" href="/en/evidence/EVD-PT-THERM-001">View technical documentation</Link></div></div></div></section>
  </>;
}
