import type { Locale } from '@/lib/i18n';
import { TechnicalVisual } from './TechnicalVisual';
import { Breadcrumb } from './Breadcrumb';
import { EvidenceBadge } from './EvidenceBadge';

const routes = {
  detail: { de: ['PURE THERMO DETAIL','Funktion dort, wo Details entscheiden.','Fensterlaibungen, Stürze, Deckenanschlüsse, Ecken und komplexe Geometrien.'], en: ['PURE THERMO DETAIL','Function where details matter.','Window reveals, lintels, ceiling connections, corners and complex geometries.'] },
  exterior: { de: ['PURE THERMO EXTERIOR','Dauerhafter Schutz für die Fassade.','Definierter System- und Prüfpfad für Außenuntergründe; UV, Schlagregen, Frost-Tau und Haftung sind objektspezifisch zu validieren.'], en: ['PURE THERMO EXTERIOR','Long-lasting protection for façades.','Defined system and validation route for exterior substrates; UV, driving rain, freeze-thaw and adhesion require object-specific validation.'] },
  fire: { de: ['PURE THERMO + PURE FIRE','Mehr Schutz. Mehr Möglichkeiten.','Entwicklungs- und Validierungsroute für einen kombinierten Systemaufbau.'], en: ['PURE THERMO + PURE FIRE','More Protection. More Possibilities.','Development and validation route for a combined system build-up.'] }
} as const;

export function ThermoSystemRoutePage({ locale, route }: { locale: Locale; route: keyof typeof routes }) {
  const copy = routes[route][locale];
  return <><Breadcrumb items={[{ label: locale === 'de' ? 'Start' : 'Home', href: locale === 'de' ? '/de' : '/en' }, { label: locale === 'de' ? 'Systemrouten' : 'System Routes' }, { label: copy[0] }]} /><section className="hero"><div className="container"><p className="hero__eyebrow">{locale === 'de' ? 'SYSTEMROUTE' : 'SYSTEM ROUTE'}</p><h1>{copy[1]}</h1><p className="hero__subtitle">{copy[2]}</p><div style={{ marginTop: 'var(--space-3)' }}><EvidenceBadge evidenceClass={route === 'fire' ? 'D' : 'B'} /></div></div></section><section className="section"><div className="container"><TechnicalVisual locale={locale} visual={route === 'detail' ? 'detail' : route === 'exterior' ? 'exterior' : 'platform'} altDe={copy[0]} altEn={copy[0]} captionDe="Illustrative Systemvisualisierung. Eignung und Systemaufbau sind objektspezifisch zu prüfen." captionEn="Illustrative system visualisation. Suitability and system build-up require object-specific assessment." /><div className="fire-protect-rule">{locale === 'de' ? 'Eine Brandklasse ist kein Materialetikett. Sie beschreibt einen konkret geprüften Aufbau.' : 'A fire classification is not a material label. It applies to a specifically tested system configuration.'}</div></div></section>{route === 'detail' ? <section className="section section--surface"><div className="container"><TechnicalVisual locale={locale} visual="thermalBridge" altDe="Illustrative bauphysikalische Darstellung von Wärmebrücken und Oberflächentemperatur." altEn="Illustrative building-physics visualisation of thermal bridges and surface temperature." captionDe="Illustrative bauphysikalische Darstellung. Tatsächliche Temperaturen hängen von Aufbau und Randbedingungen ab." captionEn="Illustrative building-physics visualisation. Actual temperatures depend on build-up and boundary conditions." /></div></section> : null}{route === 'fire' ? <section className="section section--surface"><div className="container"><TechnicalVisual locale={locale} visual="testPath" altDe="Prüfpfad für den kombinierten PURE THERMO + PURE FIRE Systemaufbau." altEn="Test path for the combined PURE THERMO + PURE FIRE system build-up." captionDe="Separate Prüfungen ergeben noch keine Kombinationsklasse." captionEn="Separate tests do not constitute a combined classification." /></div></section> : null}</>;
}
