export type SurfaceProtectLocale = 'de' | 'en';

type Pair = [string, string];

const en = {
  name: 'PURE SURFACE PROTECT', heroTitle: 'Invisible protection. Visible value.', heroSubtitle: 'Ultra-thin, transparent functional coating for façades, metal, glass and high-value surfaces — developed to support easier cleaning, reduced maintenance and longer-lasting surface appearance.', heroFacts: [['2–8 µm', 'typical functional layer logic'], ['70–90 m²/L', 'application-dependent coverage']] as Pair[], heroCta: 'Explore the technology', referencesCta: 'View references', heroCaption: 'Technology / hero visual — conceptual split-treatment effect, not a documented before/after reference.',
  challengeEyebrow: 'THE CHALLENGE', challengeTitle: 'Surfaces lose value long before components need replacement.', challengeCopy: 'UV, dirt, moisture, abrasion, graffiti and chemical exposure can affect the appearance, cleanability and retained value of surfaces. Replacement or recoating is not automatically the most economical answer for every situation.', challengeStatement: 'Not every surface needs replacement. Sometimes the existing surface needs a new function.', challengeCards: [['UV & WEATHERING', ''], ['DIRT & DEPOSITS', ''], ['ABRASION & CHEMICAL EXPOSURE', ''], ['MAINTENANCE & REFURBISHMENT', '']] as Pair[],
  techEyebrow: 'MATERIAL TECHNOLOGY', techTitle: 'Performance starts at the surface — not with layer thickness.', steps: [['WETTING', 'Substrate, surface condition and appearance target are assessed.'], ['HYBRID MATRIX', 'A very thin sol-gel / organosilane-based hybrid matrix forms the functional protective layer.'], ['BARRIER EFFECT', 'Reduced porosity is intended to reduce the penetration of moisture, pigments and deposits.'], ['CLEANING', 'Contamination remains more at the surface and can therefore be easier to remove.']] as Pair[],
  applicationsEyebrow: 'APPLICATIONS', applicationsTitle: 'One protection principle. Multiple surface environments.', applications: [['ARCHITECTURE & FAÇADES', 'Aluminium, glass, metal panels and coated façade surfaces.'], ['INFRASTRUCTURE & PUBLIC ASSETS', 'Stations, airports, bridges, railings, doors and public surfaces.'], ['INDUSTRY & MAINTENANCE', 'Machines, equipment, stainless steel and painted components.'], ['HERITAGE & HIGH-VALUE SURFACES', 'Optical preservation of high-value surfaces with as little visible change as possible.']] as Pair[],
  evidenceEyebrow: 'REAL-WORLD EVIDENCE', evidenceTitle: 'From material principle to real-world surfaces.', uaeTitle: 'MARBLE FAÇADE · UAE', uaeCopy: 'Real-world application reference on the marble façade of a bank building.', uaePoints: ['cleaner, more homogeneous appearance', 'stronger visual gloss', 'greater depth effect of the natural-stone surface'], uaeNote: 'Observed visual reference effect. This does not establish guaranteed lifetime, universal marble performance or measurable energy or cost savings.', lanuvTitle: 'Façade protection at practical scale.', lanuvFacts: [['approx. 5,000 m²', 'aluminium façade'], ['100 kg', 'documented material use'], ['4 days', 'project time according to documents'], ['4 people', 'application team according to documents']] as Pair[], lanuvNote: 'The figures come from the available project documentation. Adhesion, appearance, cleaning behaviour and durability must be assessed for each new object. LANUV is a project reference, not a product approval.',
  evidence: [['2–8 µm', 'B', 'documented product / project basis'], ['70–90 m²/L', 'B', 'documented product / project basis, application-dependent'], ['EASY-TO-CLEAN', 'B', 'technical and practical indications; object-specific test area required'], ['UV / WEATHERING', 'B', 'practical indications available; long-term data to be added'], ['ANTI-GRAFFITI', 'B / D', 'application-specific indications; cleaning test for each surface required'], ['CORROSION BARRIER', 'D', 'technically plausible development / application logic; salt / climate test required']] as [string, string, string][],
  qaEyebrow: 'APPLICATION & QUALITY ASSURANCE', qaTitle: 'Every surface starts with a test area.', qa: [['TEST AREA', 'Define the original substrate, cleaning condition and appearance target.'], ['ADHESION & APPEARANCE', 'Check wetting, gloss, colour, transparency and tactile quality.'], ['FUNCTION TEST', 'Depending on application: easy-clean, UV, abrasion, chemical, corrosion and graffiti tests.'], ['APPLICATION', 'Document method, consumption, drying and climate.'], ['ACCEPTANCE', 'Document photos, cleaning test, consumption and result.']] as Pair[], qaStatement: 'The technology is only as reliable as the documented substrate and application process.',
  lifecycleEyebrow: 'LIFECYCLE VALUE', lifecycleTitle: 'Surface value is measured across the lifecycle.', lifecycleIntro: 'Project economics can be influenced by cleaning cycles, cleaning chemistry, recoating, refurbishment intervals, downtime, retained appearance and the service life of the treated surface.', lifecycleFactors: ['cleaning cycles', 'cleaning chemistry', 'recoating', 'refurbishment intervals', 'downtime', 'retained appearance', 'service life of the treated surface'],
  limitsEyebrow: 'TECHNICAL BOUNDARIES', limitsTitle: 'What Surface Protect can support — and what must be assessed for each object.', strengths: ['ultra-thin transparent protection logic', 'high area coverage', 'easy-to-clean applications', 'broad substrate basis', 'low material use', 'object-specific protection and maintenance concepts'], limits: ['universal suitability for every substrate', 'guaranteed service life', 'universal corrosion protection', 'universal anti-graffiti effect', 'general UV / weathering duration', 'complete water tightness', 'general chemical resistance'], regulatoryEyebrow: 'REGULATORY NOTE', regulatory: 'Depending on the application, building requirements, VOC / indoor emissions, adhesion, UV / weathering, cleaning chemicals and substrate compatibility may need to be assessed. No general regulatory approval is implied.',
  finalTitle: 'Which surface should stay cleaner and valuable for longer?', finalCopy: 'We assess substrate, application, appearance target and required surface function before defining an appropriate test area.', project: 'Discuss your project', test: 'Request a test area'
} as const;

const de = {
  ...en,
  heroTitle: 'Unsichtbarer Schutz. Sichtbarer Werterhalt.', heroSubtitle: 'Ultra-dünne, transparente Funktionsbeschichtung für Fassaden, Metall, Glas und hochwertige Oberflächen – entwickelt für leichtere Reinigung, geringeren Pflegeaufwand und längere optische Nutzbarkeit.', heroFacts: [['2–8 µm', 'typische Schutzlogik'], ['70–90 m²/L', 'anwendungsabhängige Flächenleistung']] as Pair[], heroCta: 'Technologie verstehen', referencesCta: 'Referenzen ansehen', heroCaption: 'Technologie-/Hero-Visual – konzeptioneller Behandlungseffekt, keine dokumentierte Vorher-/Nachher-Referenz.',
  challengeEyebrow: 'DIE HERAUSFORDERUNG', challengeTitle: 'Oberflächen verlieren Wert, lange bevor Bauteile ersetzt werden müssen.', challengeCopy: 'UV, Schmutz, Feuchte, Abrieb, Graffiti und chemische Belastungen können Optik, Reinigbarkeit und Werterhalt von Oberflächen beeinträchtigen. Austausch oder Neulackierung ist nicht für jede Situation die wirtschaftlichste Antwort.', challengeStatement: 'Nicht immer braucht es eine neue Oberfläche. Manchmal braucht die bestehende Oberfläche eine neue Funktion.', challengeCards: [['UV & WITTERUNG', ''], ['SCHMUTZ & BELÄGE', ''], ['ABRIEB & CHEMISCHE BELASTUNG', ''], ['PFLEGE & SANIERUNG', '']] as Pair[],
  techEyebrow: 'MATERIAL TECHNOLOGY', techTitle: 'Der Hebel liegt in der Oberfläche – nicht in der Schichtdicke.', steps: [['BENETZUNG', 'Substrat, Oberflächenzustand und optisches Ziel werden geprüft.'], ['HYBRIDMATRIX', 'Eine sehr dünne Sol-Gel-/Organosilan-basierte Hybridmatrix bildet die funktionale Schutzschicht.'], ['BARRIEREEFFEKT', 'Die reduzierte Porosität soll das Eindringen von Feuchte, Pigmenten und Belägen reduzieren.'], ['REINIGUNG', 'Verschmutzungen bleiben eher an der Oberfläche und können dadurch leichter entfernt werden.']] as Pair[],
  applicationsEyebrow: 'ANWENDUNGEN', applicationsTitle: 'Eine Schutzlogik. Unterschiedliche Oberflächenwelten.', applications: [['ARCHITEKTUR & FASSADEN', 'Aluminium, Glas, Metallpaneele und beschichtete Fassadenflächen.'], ['INFRASTRUKTUR & ÖFFENTLICHE OBJEKTE', 'Bahnhöfe, Flughäfen, Brücken, Geländer, Türen und öffentliche Oberflächen.'], ['INDUSTRIE & INSTANDHALTUNG', 'Maschinen, Anlagen, Edelstahl und lackierte Bauteile.'], ['DENKMAL & HOCHWERTIGE OBERFLÄCHEN', 'Optischer Erhalt hochwertiger Oberflächen bei möglichst geringer visueller Veränderung.']] as Pair[],
  evidenceEyebrow: 'REAL-WORLD EVIDENCE', evidenceTitle: 'Vom Materialprinzip zur realen Oberfläche.', uaeTitle: 'MARMORFASSADE · UAE', uaeCopy: 'Reale Anwendungsreferenz an der Marmor-Fassade eines Bankgebäudes.', uaePoints: ['saubereres, homogeneres Erscheinungsbild', 'stärkerer visueller Glanz', 'höhere Tiefenwirkung der Natursteinoberfläche'], uaeNote: 'Beobachtete visuelle Referenzwirkung. Daraus folgen weder garantierte Lebensdauer noch universelle Performance für jede Marmorart oder messbare Energie- bzw. Kosteneinsparungen.', lanuvTitle: 'Fassadenschutz im Praxismaßstab.', lanuvFacts: [['ca. 5.000 m²', 'Aluminiumfassade'], ['100 kg', 'dokumentierter Materialeinsatz'], ['4 Tage', 'Projektzeit laut Unterlagen'], ['4 Personen', 'Applikationsteam laut Unterlagen']] as Pair[], lanuvNote: 'Die Angaben stammen aus der vorhandenen Projektdokumentation. Haftung, Optik, Reinigungsverhalten und Beständigkeit sind bei neuen Objekten objektspezifisch zu prüfen. LANUV ist eine Projektreferenz, keine Produktzulassung.',
  evidence: [['2–8 µm', 'B', 'dokumentierte Produkt-/Projektbasis'], ['70–90 m²/L', 'B', 'dokumentierte Produkt-/Projektbasis, anwendungsabhängig'], ['EASY-TO-CLEAN', 'B', 'technische und praktische Hinweise; objektbezogene Musterfläche erforderlich'], ['UV / WITTERUNG', 'B', 'Praxishinweise vorhanden; Langzeitdaten ergänzen'], ['ANTI-GRAFFITI', 'B / D', 'anwendungsbezogene Hinweise; Reinigungsversuch je Oberfläche erforderlich'], ['KORROSIONSBARRIERE', 'D', 'technisch plausible Entwicklungs-/Anwendungslogik; Salz-/Klima-Test erforderlich']] as [string, string, string][],
  qaEyebrow: 'APPLIKATION & QUALITÄTSSICHERUNG', qaTitle: 'Jede Oberfläche beginnt mit einer Musterfläche.', qa: [['MUSTERFLÄCHE', 'Originaluntergrund, Reinigungszustand und optisches Ziel definieren.'], ['HAFTUNG & OPTIK', 'Benetzung, Glanz, Farbton, Transparenz und Haptik prüfen.'], ['FUNKTIONSTEST', 'Je nach Anwendung: Easy-clean, UV, Abrieb, Chemie, Korrosion und Graffiti.'], ['APPLIKATION', 'Methode, Verbrauch, Trocknung und Klima dokumentieren.'], ['ABNAHME', 'Fotos, Reinigungsversuch, Verbrauch und Ergebnis dokumentieren.']] as Pair[], qaStatement: 'Die Technologie ist nur so belastbar wie der dokumentierte Untergrund- und Applikationsprozess.',
  lifecycleEyebrow: 'LIFECYCLE VALUE', lifecycleTitle: 'Werterhalt wird über den Lebenszyklus gerechnet.', lifecycleIntro: 'Projektwirtschaftlichkeit kann beeinflusst werden durch Reinigungszyklen, Reinigungschemie, Neulackierung, Sanierungsintervalle, Nutzungsausfall, optischen Werterhalt und die Lebensdauer der behandelten Oberfläche.', lifecycleFactors: ['Reinigungszyklen', 'Reinigungschemie', 'Neulackierung', 'Sanierungsintervalle', 'Nutzungsausfall', 'optischer Werterhalt', 'Lebensdauer der behandelten Oberfläche'],
  limitsEyebrow: 'TECHNISCHE GRENZEN', limitsTitle: 'Was Surface Protect leisten kann – und was objektspezifisch geprüft werden muss.', strengths: ['ultra-dünne transparente Schutzlogik', 'hohe Flächenleistung', 'Easy-to-clean-Anwendungen', 'breite Substratbasis', 'geringer Materialeinsatz', 'objektbezogene Schutz- und Pflegekonzepte'], limits: ['universelle Eignung für jeden Untergrund', 'garantierte Lebensdauer', 'universeller Korrosionsschutz', 'universelle Anti-Graffiti-Wirkung', 'pauschale UV-/Witterungsdauer', 'vollständige Wasserdichtigkeit', 'pauschale Chemikalienbeständigkeit'], regulatoryEyebrow: 'REGULATORY NOTE', regulatory: 'Je nach Anwendung können baurechtliche Anforderungen, VOC-/Emissionen im Innenraum, Haftung, UV/Witterung, Reinigungschemikalien und Untergrundverträglichkeit relevant sein. Eine pauschale regulatorische Freigabe wird nicht suggeriert.',
  finalTitle: 'Welche Oberfläche soll länger gut aussehen und leichter zu pflegen sein?', finalCopy: 'Wir prüfen Untergrund, Anwendung, optisches Ziel und gewünschte Schutzfunktion und definieren daraus die geeignete Musterfläche.', project: 'Projekt besprechen', test: 'Musterfläche anfragen'
} as unknown as typeof en;

export function getSurfaceProtectContent(locale: SurfaceProtectLocale) {
  return locale === 'de' ? de : en;
}
